name: Build

on:
  push:
    paths-ignore:
      - '**.md'

env:
  BUILD_TYPE: Release

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
            sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
            sudo apt-get update -y -qq
            sudo apt-get install libsdl2-dev

      - name: Configure build
        shell: bash
        run: cmake -B ${{runner.workspace}}/_build -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        shell: bash
        run: cmake --build ${{runner.workspace}}/_build

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist_linux
          path: ${{runner.workspace}}/_build/postal

