XBE_TITLE = postal
GEN_XISO = $(XBE_TITLE).iso

NXDK_SDL = y
NXDK_CXX = y

SRCS =	\
	../src/Anim3D.cpp \
	../src/AnimThing.cpp \
	../src/BufQ.cpp \
	../src/GameSettings.cpp \
	../src/IdBank.cpp \
	../src/InputSettings.cpp \
	../src/InputSettingsDlg.cpp \
	../src/MemFileFest.cpp \
	../src/MenuSettings.cpp \
	../src/MenuTrans.cpp \
	../src/Personatorium.cpp \
	../src/PowerUp.cpp \
	../src/SampleMaster.cpp \
	../src/SndRelay.cpp \
	../src/SoundThing.cpp \
	../src/StockPile.cpp \
	../src/TexEdit.cpp \
	../src/Thing3d.cpp \
	../src/TriggerRegions.cpp \
	../src/aivars.cpp \
	../src/alphablitforpostal.cpp \
	../src/ball.cpp \
	../src/band.cpp \
	../src/barrel.cpp \
	../src/bouy.cpp \
	../src/bulletFest.cpp \
	../src/camera.cpp \
	../src/character.cpp \
	../src/chunk.cpp \
	../src/crawler.cpp \
	../src/credits.cpp \
	../src/cutscene.cpp \
	../src/deathWad.cpp \
	../src/demon.cpp \
	../src/dispenser.cpp \
	../src/doofus.cpp \
	../src/dude.cpp \
	../src/encrypt.cpp \
	../src/explode.cpp \
	../src/fire.cpp \
	../src/fireball.cpp \
	../src/firebomb.cpp \
	../src/flag.cpp \
	../src/flagbase.cpp \
	../src/game.cpp \
	../src/gameedit.cpp \
	../src/grenade.cpp \
	../src/grip.cpp \
	../src/heatseeker.cpp \
	../src/hood.cpp \
	../src/input.cpp \
	../src/item3d.cpp \
	../src/keys.cpp \
	../src/localize.cpp \
	../src/logtab.cpp \
	../src/main.cpp \
	../src/menus.cpp \
	../src/mine.cpp \
	../src/napalm.cpp \
	../src/navnet.cpp \
	../src/net.cpp \
	../src/organ.cpp \
	../src/ostrich.cpp \
	../src/person.cpp \
	../src/play.cpp \
	../src/pylon.cpp \
	../src/realm.cpp \
	../src/rocket.cpp \
	../src/scene.cpp \
	../src/score.cpp \
	../src/sentry.cpp \
	../src/settings.cpp \
	../src/smash.cpp \
	../src/thing.cpp \
	../src/title.cpp \
	../src/toolbar.cpp \
	../src/trigger.cpp \
	../src/update.cpp \
	../src/warp.cpp \
	../src/weapon.cpp \
	../src/yatime.cpp \
	../src/RSPiX/Src/BLUE/unix/Bdebug.cpp \
	../src/RSPiX/Src/BLUE/unix/Bjoy.cpp \
	../src/RSPiX/Src/BLUE/unix/Bkey.cpp \
	../src/RSPiX/Src/BLUE/unix/Bmain.cpp \
	../src/RSPiX/Src/BLUE/unix/Bmouse.cpp \
	../src/RSPiX/Src/BLUE/unix/Btime.cpp \
	../src/RSPiX/Src/BLUE/unix/Bdisp.cpp \
	../src/RSPiX/Src/BLUE/unix/Bsound.cpp \
	../src/RSPiX/Src/GREEN/Hot/hot.cpp \
	../src/RSPiX/Src/GREEN/Image/Image.cpp \
	../src/RSPiX/Src/GREEN/Image/Imagecon.cpp \
	../src/RSPiX/Src/GREEN/Image/ImageFile.cpp \
	../src/RSPiX/Src/GREEN/InputEvent/InputEvent.cpp \
	../src/RSPiX/Src/GREEN/Mix/mix.cpp \
	../src/RSPiX/Src/GREEN/Mix/MixBuf.cpp \
	../src/RSPiX/Src/GREEN/Image/pal.cpp \
	../src/RSPiX/Src/GREEN/Image/PalFile.cpp \
	../src/RSPiX/Src/GREEN/Sample/sample.cpp \
	../src/RSPiX/Src/GREEN/Snd/snd.cpp \
	../src/RSPiX/Src/GREEN/SndFx/SndFx.cpp \
	../src/RSPiX/Src/GREEN/Task/task.cpp \
	../src/RSPiX/Src/GREEN/3D/pipeline.cpp \
	../src/RSPiX/Src/GREEN/3D/render.cpp \
	../src/RSPiX/Src/GREEN/3D/types3d.cpp \
	../src/RSPiX/Src/GREEN/3D/zbuffer.cpp \
	../src/RSPiX/Src/GREEN/BLiT/alphablit.cpp \
	../src/RSPiX/Src/GREEN/BLiT/BLIT.cpp \
	../src/RSPiX/Src/GREEN/BLiT/BLITINIT.cpp \
	../src/RSPiX/Src/GREEN/BLiT/BLiTT.cpp \
	../src/RSPiX/Src/GREEN/BLiT/CFNT.cpp \
	../src/RSPiX/Src/GREEN/BLiT/Fspr1.cpp \
	../src/RSPiX/Src/GREEN/BLiT/FSPR8.cpp \
	../src/RSPiX/Src/GREEN/BLiT/line.cpp \
	../src/RSPiX/Src/GREEN/BLiT/mono.cpp \
	../src/RSPiX/Src/GREEN/BLiT/Rotate96.cpp \
	../src/RSPiX/Src/GREEN/BLiT/RPrint.cpp \
	../src/RSPiX/Src/GREEN/BLiT/ScaleFlat.cpp \
	../src/RSPiX/Src/ORANGE/GameLib/ANIMSPRT.cpp \
	../src/RSPiX/Src/ORANGE/Attribute/attribute.cpp \
	../src/RSPiX/Src/ORANGE/GUI/btn.cpp \
	../src/RSPiX/Src/ORANGE/Channel/channel.cpp \
	../src/RSPiX/Src/ORANGE/color/colormatch.cpp \
	../src/RSPiX/Src/ORANGE/DirtRect/DirtRect.cpp \
	../src/RSPiX/Src/ORANGE/color/dithermatch.cpp \
	../src/RSPiX/Src/ORANGE/GUI/dlg.cpp \
	../src/RSPiX/Src/ORANGE/GUI/edit.cpp \
	../src/RSPiX/Src/ORANGE/File/file.cpp \
	../src/RSPiX/Src/ORANGE/QuickMath/FixedPoint.cpp \
	../src/RSPiX/Src/ORANGE/GUI/guiItem.cpp \
	../src/RSPiX/Src/ORANGE/IFF/iff.cpp \
	../src/RSPiX/Src/ORANGE/ImageTools/lasso.cpp \
	../src/RSPiX/Src/ORANGE/Laymage/laymage.cpp \
	../src/RSPiX/Src/ORANGE/GUI/ListBox.cpp \
	../src/RSPiX/Src/ORANGE/GUI/ListContents.cpp \
	../src/RSPiX/Src/ORANGE/Meter/meter.cpp \
	../src/RSPiX/Src/ORANGE/MsgBox/MsgBox.cpp \
	../src/RSPiX/Src/ORANGE/GUI/MultiBtn.cpp \
	../src/RSPiX/Src/ORANGE/MultiGrid/MultiGrid.cpp \
	../src/RSPiX/Src/ORANGE/MultiGrid/MultiGridIndirect.cpp \
	../src/RSPiX/Src/ORANGE/GUI/ProcessGui.cpp \
	../src/RSPiX/Src/ORANGE/Debug/profile.cpp \
	../src/RSPiX/Src/ORANGE/GUI/PushBtn.cpp \
	../src/RSPiX/Src/ORANGE/QuickMath/QuickMath.cpp \
	../src/RSPiX/Src/ORANGE/QuickMath/Fractions.cpp \
	../src/RSPiX/Src/ORANGE/GameLib/Region.cpp \
	../src/RSPiX/Src/ORANGE/RString/rstring.cpp \
	../src/RSPiX/Src/ORANGE/GUI/scrollbar.cpp \
	../src/RSPiX/Src/ORANGE/GameLib/SHAPES.cpp \
	../src/RSPiX/Src/ORANGE/Parse/SimpleBatch.cpp \
	../src/RSPiX/Src/ORANGE/GameLib/SPRITE.cpp \
	../src/RSPiX/Src/ORANGE/str/str.cpp \
	../src/RSPiX/Src/ORANGE/GUI/txt.cpp \
	../src/RSPiX/Src/CYAN/Unix/uDialog.cpp \
	../src/RSPiX/Src/CYAN/Unix/uColors.cpp \
	../src/RSPiX/Src/CYAN/Unix/uPath.cpp \
	../src/WishPiX/Menu/menu.cpp \
	../src/WishPiX/Prefs/prefline.cpp \
	../src/WishPiX/Prefs/prefs.cpp \
	../src/WishPiX/ResourceManager/resmgr.cpp \
	../src/WishPiX/Spry/spry.cpp \
	nxdk_file_utils.cpp	\

#	../src/Log.cpp \
#	../src/NetBrowse.cpp \
#	../src/NetClient.cpp \
#	../src/NetDlg.cpp \
#	../src/NetServer.cpp \
#	../src/ProtoBSDIP.cpp \
#	../src/netmsgr.cpp \
#	../src/socket.cpp \

CXXFLAGS += -I../src
CXXFLAGS += -I../src/RSPiX
CXXFLAGS += -I../src/RSPiX/Inc
CXXFLAGS += -I../src/RSPiX/Src
CXXFLAGS += -I../src/RSPiX/Src/BLUE
CXXFLAGS += -I../src/RSPiX/Src/BLUE/unix
CXXFLAGS += -I../src/RSPiX/Src/CYAN
CXXFLAGS += -I../src/RSPiX/Src/CYAN/Unix
CXXFLAGS += -I../src/RSPiX/Src/ORANGE
CXXFLAGS += -I../src/RSPiX/Src/ORANGE/CDT
CXXFLAGS += -I../src/RSPiX/Src/ORANGE/GameLib
CXXFLAGS += -I../src/RSPiX/Src/ORANGE/File
CXXFLAGS += -I../src/RSPiX/Src/ORANGE/Multigrid
CXXFLAGS += -I../src/RSPiX/Src/GREEN/Image
CXXFLAGS += -I../src/WishPiX
CXXFLAGS += -I../src/WishPiX/Spry

CXXFLAGS += -DPLATFORM_NXDK
CXXFLAGS += -DLOCALE=US
CXXFLAGS += -DTARGET=POSTAL_2015
CXXFLAGS += -DALLOW_TWINSTICK
CXXFLAGS += -DEDITOR_DISABLED -DMULTIPLAYER_DISABLED -DMULTIPLAYER_REMOVED

include $(NXDK_DIR)/Makefile
